In [1]:
import pandas as pd

In [35]:
df = pd.read_csv("/opt/predii/isha/enginuity/results/data-13/table_data/page_194/page_194.csv",sep="\t")

In [36]:
df

,(1) ITEM NO,(2) SMR CODE,(3) NSN,(4) CAGEC,(5) PART NUMBER,(6) DESCRIPTION AND USABLE ON CODES (UOC),(7) QTY
0,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH, ZAJ,ZAK,ZAL",NaN
1,17.0,PFHZZ,5.360013e+12,53867,1 414 618 030,"SPRING,HELICAL,COMP",6
2,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH, ZAJ,ZAK,ZAL",NaN
3,18.0,PFHZZ,5.340013e+12,53867,1 410 505 015,"SEAT,HELICAL COMPRE",6
4,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH, ZAJ,ZAK,ZAL",NaN
5,19.0,PFHZZ,2.910013e+12,53867,1 410 422 031,"SLEEVE,GOVERNOR,FUE",6
6,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH, ZAJ,ZAK,ZAL",NaN
7,20.0,PFHZZ,5.331013e+12,53867,1410210503,O-RING 16 X 3MM PART OF KIT P/N 1,6
8,NaN,NaN,NaN,NaN,NaN,417 010 008,NaN
9,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH, ZAJ,ZAK,ZAL",NaN
10,21.0,PFHZZ,5.365013e+12,53867,1 410 290 005,"SPACER,RING PART OF KIT P/N 1 417",6
11,NaN,NaN,NaN,NaN,NaN,010 008,NaN
12,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH,- ZAJ,ZAK,ZAL",NaN
13,22.0,KFHZ,NaN,5T151,1 414 601 004,RETAINER RING PART OF KIT P/N 1 417,6
14,NaN,NaN,NaN,NaN,NaN,010 008,NaN
15,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH, ZAJ,ZAK,ZAL",NaN
16,23.0,PFHZZ,5.365013e+12,3867,1 410 505 023,"SPACER,SLEEVE",6
17,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH, ZAJ,ZAK,ZAL",NaN
18,24.0,PFHZZ,5.331013e+12,53867,1 410 210 501,O-RING 19 X 2MM PART OF. KIT P/N 1.,6
19,NaN,NaN,NaN,NaN,NaN,417 010 008,NaN
20,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH, ZAJ,ZAK,Z...",NaN
21,25.0,PFHZZ,5.365013e+12,53867,1 411 030 134,"SPACER,PLATE 1.00 MM THICK",V
22,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH, ZAJ,ZAK,ZAL",NaN
23,25.0,PFHZZ,5.365013e+12,53867,1 411 030 135,"SPACER,PLATE 1.05MM THICK",V
24,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH, ZAJ,ZAK,ZAL",NaN
25,25.0,PFHZZ,5.365013e+12,53867,1 411 030 136,"SPACER,PLATE 1.10MM THICK",V
26,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH, ZAJ,ZAK,ZAL",NaN
27,25.0,PFHZZ,5.365013e+12,53867,1 411 030 137,"SPACER,PLATE 1.15MM THICK",V
28,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH, ZAJ,ZAK,ZAL",NaN
29,25.0,PFHZZ,5.365013e+12,53867,1 411 030 138,"SPACER,PLATE 1.20MM THICK",V
30,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH, ZAJ,ZAK,ZAL",NaN
31,25.0,PFHZZ,5.365013e+12,53867,1 411 030 139,"SPACER,PLATE 1.25MM THICK",V
32,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH, ZAJ,ZAK,ZAL",NaN
33,25.0,PFHZZ,5.365013e+12,53867,1 411 030 140,"SPACER,PLATE 1.30MM THICK",V
34,NaN,NaN,NaN,NaN,NaN,"UOC:ZAA,ZAB,ZAC,ZAD,ZAE,ZAF,ZAG,ZAH, ZAJ,ZAK,ZAL",NaN
35,25.0,PFHZZ,5.365013e+12,53867,1 411 030 141,"SPACER,PLATE 1.35MM THICK",V

In [33]:
cols = ["FIG_NO", "ITEM_NO", "SMR_CODE", "STOCK_NUMBER", "CAGE", "PART_NUMBER", "DESCRIPTION", "UM", "QTY"]

df = pd.read_csv(
    "/opt/predii/tilak/enginuity/tsv_output/data-2/page_98.tsv",
    sep="\t",
    skiprows=7,
    names=cols
)

In [34]:
df

,FIG_NO,ITEM_NO,SMR_CODE,STOCK_NUMBER,CAGE,PART_NUMBER,DESCRIPTION,UM,QTY
0,32,62,KFHZZ,. . .,72582,5150372,.SHIM .002. PART OF KIT P/N 23514202,EA,1
1,32,62,KFHZZ,. . .,72582,5150855,.SHIM .005. PART OF KIT P/N 23514202,EA,1
2,32,62,KFHZZ,. . .,24617,5150856,.SHIM .O1O. PART OF KIT P/N 23514202,EA,1
3,32,62,KFHZZ,. . .,72582,5153938,.SHIM .003. PART OF KIT P/N 23514202,EA,1
4,32,63,PFHZZ,3020-005-591-8122,72582,5196321,"GEAR SET, HELICAL CONTAINS RH AND LH GEARS",EA,1
5,32,64,XAHZZ,NaN,72582,5117079,.GEAR,EA,1
6,32,65,XAHZZ,NaN,72582,5125849,.GEAR,EA,1
7,32,66,PFHZZ,5365-01-059-3438,72582,5146049,SPACER,EA,2
8,32,67,PAHZZ,5305-01-058-4512,72582,9409060,"SCREW, MACHINE 1/2-20 X 1 1/2",EA,1
9,32,68,PAHZZ,5305-01-165-3265,72582,5147149,"SCREW, MACHINE 1/2-20 x 1 1/2",EA,1
10,32,69,PAFZZ,5330-01-166-1020,72582,8923959,"SEAL, RING",EA,1
11,32,70,PAFZZ,4820-01-270-6456,72582,8927187,.VALVE BYPASS,EA,1